pipeline {

    agent any

    stages {

        stage('Build') {
            steps {
                sh './jenkins/build/mvn.sh -B -DskiptTests clean package'
                sh './jenkins/build/build.sh'
            }
        }
    }
}

